export {default as Home} from './Home'
export {default as News} from './News'
export {default as Contact} from './Contact'
export {default as Upload} from './Upload'
export {default as Search} from './Search'
export {default as Profile} from './Profile'
export {default as Live} from './Live'